spring-quiz:
  title: "\"Тест по Spring Framework\""
  report:
    # spring-quiz.report.enabled — нужно ли формировать отчёт
    enabled: true
    # spring-quiz.report.mode — режим формирования отчёта;
    # может иметь одно из двух значений:
    # verbose — формировать расширенный отчёт
    # concise — формировать сокращённый отчёт
    mode: "concise"
    # spring-quiz.report.output — настройки вывода отчёта
    output:
      # spring-quiz.report.output.mode — режим вывода отчёта;
      # может иметь одно из двух значений:
      # console — вывод отчёта в консоль
      # file — вывод отчёта в файл
      mode: "file"
      # spring-quiz.report.output.path — путь к файлу,
      # в который необходимо записать данные отчёта
      path: "./quiz-result.txt"

spring:
  config:
    import: "classpath:quiz/questions.yaml"
  main:
    log-startup-info: false
    banner-mode: console
  output:
    ansi:
      enabled: always